### PR TITLE
cn0398: fix ph computation formula

### PR DESCRIPTION
**Pull request by amiclaus**
According to the Circuit Note offset voltage should be substracted
instead of added.

Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>

### CODE REVIEW

**Comment by mirceacaprioru** [comment]
Is this fix also required for ADICUP3029 ?

**Comment by amiclaus** [comment]
Indeed. I will do a PR after this one is approved.

**Comment by bbushey** [comment]
Can we please also check the CN0398 project as well?  There is a pH sensor in there, and if the code was reused, than this issue would have been replicated there as well.

Cheers,

Brandon

**Comment by amiclaus** [comment]
The fix is done both in the GreenHouse project and CN0398 project.

**Pull request merged**
